network:
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.0.10/24
      nameservers:
        addresses: [192.168.0.1, 8.8.8.8]
      routes:
        - to: default
          via: 192.168.0.1
  version: 2